[build]
base = "/"
publish = "dist"
command = "npm run build"

[context.production]
environment = { NODE_ENV = "production" }

[context.preview]
environment = { NODE_ENV = "preview" }

[[redirects]]
from = "/old"
to = "/new"
status = 301

[[headers]]
for = "/*"
[headers.values]
X-XSS-Protection = "1; mode=block"
