[build]
  base = "/"
  publish = "frontend/dist"
  command = """
    sudo apt-get update
    sudo apt-get install -y --no-install-recommends gfortran
    sudo apt-get install -y libatlas-base-dev liblapack-dev
    pip install --upgrade pip
    pip install -r requirements.txt
  """

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "deploy-preview" }

[dev]
  command = "npm run serve"
  port = 3000
