[build]
  base = "/"
  publish = "frontend/dist"
  command = """
    apt-get update
    apt-get install -y gfortran
    pip install -r requirements.txt
  """

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "deploy-preview" }

[dev]
  command = "npm run serve"
  port = 3000
