name: Deploy Ai_RiQA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install backend dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run backend tests
      run: |
        cd backend
        python -m pytest
        
    - name: Build and start containers
      run: |
        docker-compose up -d --build
        sleep 10  # Wait for services to start
        
    - name: Run end-to-end tests
      run: |
        cd frontend
        npm install
        npm run test:e2e
